server:
  port: 8090

spring:
  application:
    name: customer-service
  data:
    mongodb:
      #same as docker compose file
      username: csage
      password: password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin