server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #true to connect to discovery service
      routes:
        #These are the publicly exposed endpoints available via the gateway
        #uri uses load balancer(lb:), then host - matches the eureka service id
        #predicates redirects the request listed to the uri for load balancing, or other predicates such as headers, etc
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/order-lines/**
        - id: products-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: payment-service #TODO: add mechanism to allow only internal calls
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
