#inherit base values from application.yml, such as eureka info
server:
  port: 8050

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: csage
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 1