server:
  port: 8888

spring:
  profiles:
    # use the native profile for AOT classpath processing
    active: native
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          # search for configuration files here.  can be GitHub/url or classpath
          search-locations: classpath:/configurations
